name: Publish provider packages

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +lint

  build-provider-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v3
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: echo "${{ secrets.ARTIFACT_IMG_PUSH_EDGE }}" | base64 -d | docker login -u _json_key --password-stdin us-docker.pkg.dev
      - run: earthly --ci --push --output +provider-package-all-platforms --IMAGE_REPOSITORY=us-docker.pkg.dev/palette-images/edge/kairos-io
