name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - run: earthly --ci +lint
      - run: earthly --ci +test

  build-provider-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - run: earthly --ci --output  +provider-package-all-platforms --IMAGE_REPOSITORY=ghcr.io/kairos-io
      - name: Push to testing
        run: |
          docker tag ghcr.io/kairos-io/provider-nodeadm:latest ttl.sh/kairos-io/provider-nodeadm-${{ github.sha }}:24h
          docker push ttl.sh/kairos-io/provider-nodeadm-${{ github.sha }}:24h