name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +lint
      - run: earthly --ci +test

  build-provider-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v3
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - run: earthly --ci --output  +provider-package-all-platforms --IMAGE_REPOSITORY=ghcr.io/kairos-io
      - name: Push to testing
        run: |
          docker tag ghcr.io/kairos-io/provider-nodeadm:latest ttl.sh/kairos-io/provider-nodeadm-${{ github.sha }}:24h
          docker push ttl.sh/kairos-io/provider-nodeadm-${{ github.sha }}:24h